# Generated by Django 4.1 on 2022-09-05 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('caronaId', models.AutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('rota', models.CharField(max_length=300)),
                ('custo', models.IntegerField()),
                ('finalizada', models.BooleanField(default=False)),
                ('passageiros', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('validado', models.BooleanField(default=False)),
                ('aval', models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MobiCampus.usuario')),
                ('permissao', models.BooleanField()),
            ],
            bases=('MobiCampus.usuario',),
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MobiCampus.usuario')),
                ('cnh', models.CharField(max_length=11)),
            ],
            bases=('MobiCampus.usuario',),
        ),
        migrations.CreateModel(
            name='CaronaAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MobiCampus.carona')),
                ('passageiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passageiro', to='MobiCampus.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='carona',
            name='motorista',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MobiCampus.motorista'),
        ),
    ]
