# Generated by Django 4.1 on 2022-09-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobiCampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aceito', models.BooleanField()),
                ('Motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Motorista', to='MobiCampus.motorista')),
                ('Passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Passageiro', to='MobiCampus.usuario')),
            ],
        ),
    ]
