# Generated by Django 4.1 on 2022-10-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobiCampus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'Péssimo'), ('2', 'Ruim'), ('3', 'Regular'), ('4', 'Bom'), ('5', 'Ótimo')], max_length=1, verbose_name='Avaliação')),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='motorista',
            name='totalNotas',
            field=models.SmallIntegerField(default=0),
        ),
    ]
