# Generated by Django 4.1 on 2022-09-06 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobiCampus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobiCampus.motorista'),
        ),
    ]
