# Generated by Django 4.1 on 2022-09-24 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobiCampus', '0002_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caronahist',
            name='carona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobiCampus.carona'),
        ),
    ]
